stages:
  - build
  - deploy

build:
  image: node:lts
  stage: build
  cache:
    paths:
      - frontend/node_modules/
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build/

pages:
  image: node:lts
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - cp frontend/build/index.html frontend/build/404.html
    - mv frontend/build public
  artifacts:
    paths:
    - public
  only:
    - main
