image: node:lts

cache:
  paths:
  - frontend/node_modules

pages:
  script:
    - cd frontend && npm install
    - npm run build
    - mv public _public
    - mv build public

  artifacts:
    paths:
    - public

  only:
    - main
